cayleygraph/cayley

- AUTHORS
- CONTRIBUTORS
- db/repl.go
- db/repl_test.go
- docs/Overview.md
- graph/bolt/quadstore.go
- graph/iterator/mock_ts_test.go
- graph/leveldb/leveldb_test.go
- graph/leveldb/quadstore.go
- graph/memstore/quadstore.go
- graph/mongo/quadstore.go
- graph/primarykey.go
- graph/quadstore.go
- graph/quadwriter.go
- keys/sequentialkey.go
- writer/single.go
Fixes https://github.com/google/cayley/issues/191
I have agreed to the CLA
> Prevents repl panic

- docs/Configuration.md
- docs/GremlinAPI.md
Just a few grammar issues that stood out to me as I was reading up
> Misspellings in Gremlin and Config docs

- TODO.md
- docs/Configuration.md
- docs/GremlinAPI.md
> A couple of small spelling fixes in the docs

- graph/bolt/bolt_test.go
- graph/bolt/quadstore.go
- graph/primarykey.go
Based on LevelDB test exactly. Sure enough, it found a bug.
> Fix PrimaryKey Marshalling and add Bolt test

- AUTHORS
- CONTRIBUTORS
> Add myself to AUTHORS + CONTRIBUTORS

- graph/iterator.go
- graph/iterator/unique_iterator.go
- graph/iterator/unique_iterator_test.go
Uniqueness is a feature request people have asked for before -- returning the first path to some node in the middle of a query tree.
> Implement the Unique iterator

- .gitignore
- cmd/cayley/cayley.go
- integration/integration_test.go
- internal/load.go
- util/load.go
See the first commit for more details.  I'm not super-happy with creating *another* package, but I didn't want to duplicate code.
cc #208 and @kortschak
> Refactor packages

- graph/primarykey.go
> graph: remove redundant type

- .travis.yml
- graph/memstore/iterator.go
- graph/memstore/quadstore.go
minor code shuffle to move `cmp` into the file where it's used
> move cmp to where it's used

- graph/bolt/quadstore.go
If `NewQuadStore` was called without first calling `InitQuadStore`, the runtime would panic since the meta bucket never was created.
Feel free to close this PR and do it differently. Ran into this bug when I explored cayley for the first time. Hopefully it saves more gopher puppies from running into a nil pointer panic.
I signed the agreement in case.
> Fix nil pointer panic when meta bucket is missing

- graph/memstore/quadstore.go
i'm reading the code to try to comprehend how everything is implemented and it looked like these 2 iterations could be collapsed into 1.  let me know if i've missed something subtle.
> collapse 2 iterations into 1 in memstore

- graph/bolt/bolt_test.go
- graph/bolt/iterator.go
> Fix bug where first Bolt iteration ignores deletion

- query/gremlin/build_iterator.go
- query/gremlin/gremlin_test.go
- query/gremlin/traversals.go
> In out predicates

- graph/path/morphism_apply_functions.go
- graph/path/path.go
- graph/path/path_test.go
> Add Save and Has API functions

- AUTHORS
- CONTRIBUTORS
- TODO.md
> Added myself to the A+C

- Godeps/Godeps.json
- graph/primarykey.go
- graph/primarykey_test.go
> Use new import path for go-uuid

- db/repl.go
Forgive me if these are naive, but here are a couple small modifications I made to the REPL.
> Small REPL Improvements

- graph/iterator/mock_ts_test.go
- graph/iterator/value_comparison_iterator.go
- graph/iterator/value_comparison_iterator_test.go
i was reading the code and saw a TODO to add string comparison to the value comparison iterator.  i thought it was within my reach to tackle it so here's my attempt.  let me know what you think.
> add string comparison to value comparison iterator

- graph/bolt/quadstore.go
@barakmich Please take a look.
> graph/bolt: don't panic on unitialised store

- cmd/cayleyupgrade/cayleyupgrade.go
- graph/sql/quadstore.go
A couple call-sites changed in between, but all pretty minor.
> Fix corners after causing a couple merges

- query/gremlin/build_iterator.go
- query/gremlin/gremlin_test.go
D'oh. At least my new code coverage tool works. "Wait, what's that red block... oh, no...."
> query/gremlin: fix building Or iterator, add test

- graph/sql/quadstore.go
Counting on PostgreSQL could be really slow because of its MVCC model,
if noSizes is enabled, we should use an estimate
Ref: https://wiki.postgresql.org/wiki/Count_estimate
(CLA Accepted)
> Use a Size() estimate for SQL Quadstore when noSizes is enabled.

- graph/sql/quadstore.go
It appears that preparing an INSERT statement on PostgreSQL actually makes it expecting to receive INSERTs and thus, it create some kind of locks for it. If instead, you only send him DELETE statements, it will indefinitely wait for an INSERT and hung.
> Fix a deadlock behavior with DELETE transactions

- cmd/cayley/cayley.go
- graph/bolt/bolt_test.go
- graph/bolt/quadstore.go
- graph/leveldb/leveldb_test.go
- graph/leveldb/quadstore.go
- graph/quadstore.go
- graph/sql/quadstore.go
For use in #347, as well as general user-friendliness and cleanup.
> graph: make quadstore init functions idempotent

- Dockerfile
> dockerfile: fix go install command

- docs/GremlinAPI.md
- graph/iterator.go
- graph/iterator/limit_iterator.go
- graph/iterator/limit_iterator_test.go
- graph/iterator/skip_iterator.go
- graph/iterator/skip_iterator_test.go
- graph/path/morphism_apply_functions.go
- graph/path/path.go
- graph/path/path_test.go
- query/gremlin/build_iterator.go
- query/gremlin/gremlin_test.go
- query/gremlin/traversals.go
Addresses #352 and #121 to some extent.
Required for serialization of concrete path types (#368).
I have signed the CLA.
> Skip and Limit iterators

- clog/clog.go
> clog: fix comment typos and add package comment

- graph/memstore/quadstore.go
Makes ApplyDeltas slightly faster when checking is not strictly necessary
> Don't iterate over all quads unless necessary

- cmd/cayley/cayley.go
- graph/bolt/quadstore.go
- graph/leveldb/quadstore.go
- graph/memstore/quadstore.go
- graph/mongo/quadstore.go
- graph/quadwriter.go
- writer/single.go
This leads the way to a richer error handling that may allow the reduction of logging within packages.
> graph: provide more meaningful errors for bad actions

- graph/gaedatastore/quadstore.go
- quad/cquads/cquads_test.go
I found a few misspells in source code.
> Fix minor typos

- data/testdata.nq
- docs/GremlinAPI.md
Replaced angle brackets with quotes in testdata.
Added ".All()" to most examples
Updated some comments about result sets.
Fixed some cut-and-paste errors.
> Updated examples so that they work in repl/http.

- cmd/cayley/cayley.go
- glide.lock
- glide.yaml
- integration/integration_test.go
- query/gizmo/environ.go
- query/gizmo/errors.go
- query/gizmo/finals.go
- query/gizmo/gizmo.go
- query/gizmo/gizmo_test.go
- query/gizmo/traversals.go
- static/js/cayley_main.js
- templates/sidebar.tmpl
Switch JS VM from Otto to Goja and name this query language Gizmo.
Benchmarks (with https://github.com/dop251/goja/pull/12 merged):
```
benchmark                                     old ns/op     new ns/op     delta
BenchmarkNamePredicate-8                      169447        133728        -21.08%
BenchmarkLargeSetsNoIntersection-8            9474013       8246870       -12.95%
BenchmarkVeryLargeSetsSmallIntersection-8     23505905      20423973      -13.11%
BenchmarkHelplessContainsChecker-8            34720988      31287961      -9.89%
BenchmarkHelplessNotContainsFilms-8           35750687      32215110      -9.89%
BenchmarkHelplessNotContainsActors-8          37780076      33983268      -10.05%
BenchmarkNetAndSpeed-8                        1494604       1103341       -26.18% …
```
> Switch to Goja (introduce Gizmo)

- graph/memstore/all_iterator.go
- graph/memstore/iterator.go
- graph/memstore/quadstore.go
- graph/memstore/quadstore_iterator_optimize.go
```
benchmark                                     old ns/op     new ns/op     delta
BenchmarkNamePredicate-8                      197757        204327        +3.32%
BenchmarkLargeSetsNoIntersection-8            4130486       3369865       -18.41%
BenchmarkVeryLargeSetsSmallIntersection-8     7823824       6172993       -21.10%
BenchmarkHelplessContainsChecker-8            2606138       2199486       -15.60%
BenchmarkHelplessNotContainsFilms-8           762388        693591        -9.02%
BenchmarkHelplessNotContainsActors-8          11091629      7148805       -35.55%
BenchmarkNetAndSpeed-8                        878364        794230        -9.58%
BenchmarkKeanuAndNet-8                        605243        598530        -1.11%
BenchmarkKeanuAndSpeed-8                      722900 …
```
> memstore: optimize

- appengine/appengine.go
- cmd/cayley/cayley.go
- glide.lock
- glide.yaml
- graph/path/morphism_apply_functions.go
- graph/path/path.go
- query/graphql/graphql.go
- query/graphql/graphql_test.go
- query/graphql/http.go
- static/js/cayley_main.js
- templates/sidebar.tmpl
Adds support  for GraphQL query language. Resolves #370.
Warning: work in progress, should not be merged yet.
**TODO:**
> GraphQL support

- cmd/cayley/cayley.go
- cmd/cayley/command/convert.go
> Register glog flags, make conv an alias for convert.

- graph/sql/cockroach.go
- graph/sql/cockroach_test.go
- graph/sql/quadstore.go
Added a function CreateSQLTables on flavor struct for optional "flavor specific" creation of tables/indexes.
Cockroach beta-20170413 release notes:
https://www.cockroachlabs.com/docs/beta-20170413.html#sql-language-changes
> cockroach: schema changes within transactions are restricted

- cmd/cayley/cayley.go
- cmd/cayley/command/repl.go
- docs/Quickstart-As-Application.md
Some glog changes have broken repl and deprecated documentation.
> Glog issues

- cmd/cayley/cayley.go
- cmd/cayley/command/repl.go
- docs/Quickstart-As-Application.md
- graph/gaedatastore/quadstore.go
- graph/graphtest/graphtest.go
Possible fix for #578 Unable to re-add previously deleted Quads
> #578 re-add previously deleted quads

- cmd/cayley/command/repl.go
read the query from stdin for large queries.
> query from stdin

- graph/bolt2/bolt.go
- graph/bolt2/bolt_test.go
- graph/kv/all_iterator.go
- graph/kv/indexing.go
- graph/kv/indexing_test.go
- graph/kv/iterators.go
- graph/kv/quad_iterator.go
- graph/kv/quadstore.go
- graph/kv/quadstore_iterator_optimize.go
Make a generic KV backend based on Bolt.
Benchmarks shows only a random noise, so at least it does not hurts performance.
```
benchmark                                     old ns/op     new ns/op     delta
BenchmarkNamePredicate-8                      123620        121928        -1.37%
BenchmarkLargeSetsNoIntersection-8            11546478      11193748      -3.05%
BenchmarkVeryLargeSetsSmallIntersection-8     20313099      19839123      -2.33%
BenchmarkHelplessContainsChecker-8            703804251     670880049     -4.68%
BenchmarkHelplessNotContainsFilms-8           703763546     678679708     -3.56%
BenchmarkHelplessNotContainsActors-8          699743599     685286832     -2.07%
BenchmarkNetAndSpeed-8                        1139628       1128880       -0.94%
BenchmarkKeanuAndNet-8 …
```
> Generic KV backend based on Bolt2

- graph/kv/quadstore.go
> kv: Make bloom filter buffer before initialisation

- .travis.yml
- cmd/cayley/command/dedup.go
- cmd/cayley/command/repl.go
- docs/Contributing.md
- graph/bolt/bolt_test.go
- graph/graphtest/graphtest.go
- graph/iterate.go
- graph/leveldb/leveldb_test.go
- graph/path/path.go
- graph/path/pathtest/pathtest.go
- integration/integration_test.go
- internal/db/repl.go
- internal/gephi/stream.go
- internal/http/query.go
- quad/pquads/pquads_test.go
- query/gizmo/gizmo.go
- query/gizmo/gizmo_test.go
- query/graphql/graphql.go
- query/graphql/graphql_test.go
- query/graphql/http.go
- query/mql/mql_test.go
- query/mql/session.go
- query/session.go
- query/sexp/parser_test.go
- query/sexp/session.go
- schema/schema.go
- schema/schema_test.go
- server/http/api_v2.go
> Switch to Go 1.7

- .travis.yml
- docs/Contributing.md
- graph/bolt2/bolt.go
- graph/graphtest/graphtest.go
- graph/kv/all_iterator.go
- graph/kv/btree/Makefile
- graph/kv/btree/btree.go
- graph/kv/btree/btree_test.go
- graph/kv/btree/keys.go
- graph/kv/indexing.go
- graph/kv/iterators.go
- graph/kv/kv.go
- graph/kv/quad_iterator.go
- graph/kv/quadstore.go
- graph/quadstore.go
- integration/integration_test.go
- internal/db/db.go
- query/graphql/graphql.go
Optimize KV interface and implementation to support more efficient reads/writes, especially for remote backends.
bolt2 also receives performance boost because of this change (15-60%):
```
benchmark                                     old ns/op     new ns/op     delta
BenchmarkNamePredicate-8                      118783        143410        +20.73%
BenchmarkLargeSetsNoIntersection-8            11655012      7952428       -31.77%
BenchmarkVeryLargeSetsSmallIntersection-8     21012045      16882451      -19.65%
BenchmarkHelplessContainsChecker-8            668915823     284239893     -57.51%
BenchmarkHelplessNotContainsFilms-8           668367233     285839315     -57.23%
BenchmarkHelplessNotContainsActors-8          673131537     287670777     -57.26%
BenchmarkNetAndSpeed-8 …
```
> kv: refactor and optimize

- docs/Contributing.md
Didn't see any docs regarding running unit tests, so I thought it was helpful to add it into the contribution docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/640)
> Add running local unit test documentation

- AUTHORS
- CONTRIBUTORS
- internal/http/http.go
Fixes: https://github.com/cayleygraph/cayley/issues/672
> Adds locations for looking up static assets

- static/js/cayley_visualize.js
And caused the visualizer to stay blank when running queries.
> Javascript error from sigma.js was not visible

- graph/iterator/recursive.go
should have been unlimited, according to documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/679)
> maxDept -1 resulted in 0 results

- quad/jsonld/jsonld.go
I ran into this one and think that this pull request should solve the issue.
https://stackoverflow.com/questions/44424702/how-to-store-ldjson-data-to-cayley
> jsonld: invalid memory address or nil pointer dereference

- examples/hello_bolt/main.go
If TempFile is used cayley.NewGraph complains about
tmpfile.Name() not being a dir.
> hello_bolt: replace TempFile with TempDir

- docs/k8s/cayley-single.yml
v0.7.3 appears to be the latest stable release on quay.io
> cayley-single.yml: update version tag to latest

- graph/nosql/mongo/mongo.go
> Correct db name using mongo backend

- graph/graphmock/graphmock.go
Found by [go-critic](https://github.com/go-critic/go-critic) `typeSwitch`
Log:
```
check-package: cayley/graph/graphmock/graphmock.go:67:2: typeSwitchVar: case 0 can benefit from type switch with assignment
check-package: cayley/graph/graphmock/graphmock.go:67:2: typeSwitchVar: case 1 can benefit from type switch with assignment
```
> Use type-switch

- docs/GizmoAPI.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/789)
> Document RegEx

- README.md
Please take a look.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/799)
> README: update testing badge

- graph/iterator/regex.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/834)
> Gizmo: Apply regex filter to lang strings as well

- Dockerfile
Fixes #837
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/839)
> Adds required directory of HTTP API v1

- docs/Configuration.md
- Added paragraph about default configuration
- Added more structure
- Organized by priority
- Added index of contents
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/840)
> Update configuration docs

- .gitignore
- README.md
- docs/Contributing.md
update Contributing, adding some instructions #782
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/836)
> update docs/Contributing.md #782

- client/client.go
- cmd/cayley/cayley.go
- cmd/cayley/command/http.go
- cmd/cayley/command/repl.go
- graph/gaedatastore/quadstore.go
- graph/kv/quadstore.go
- graph/registry.go
- query/gizmo/finals.go
- schema/schema.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/867)
> Fix some lint errors

- README.md
Fix redirect to correct files in README.md.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/869)
> Fix redirect to correct files.

- graph/iterator/linksto.go
- graph/iterator/linksto_test.go
- graph/iterator/query_shape_test.go
- graph/kv/quad_iterator.go
- graph/quadstore.go
* Fix KV QuadIterator getSize()
* Fix LinksTo getSize()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/875)
> Fix Out() In Large KV

- docs/getting-started.md
...the old link 404d
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/883)
> Fix broken install.md link

- go.mod
- go.sum
- query/linkedql/schema.go
- query/linkedql/schema_test.go
- query/linkedql/steps.go
This PR implements OWL schema generation for LinkedQL to be used for code generation in client libraries. The only missing part is including comments for docs and testing properly.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/881)
> LinkedQL Schema

- graph/gaedatastore/config.go
- graph/graphtest/graphtest.go
- graph/hasa.go
- graph/iterator/and_optimize.go
- graph/iterator/fixed.go
- graph/iterator/iterator.go
- graph/iterator/resolver.go
- graph/linksto.go
- graph/quadwriter.go
- graph/sql/quadstore.go
- internal/http/query.go
- internal/lru/lru.go
- query/graphql/graphql_test.go
- query/path/pathtest/pathtest.go
- server/http/api_v2.go
Trying to get `golint ./... | grep -v "a blank import" | grep -v "comment on exported method " | grep -v "should have comment or be unexported" 
| grep -v "should have comment (or a comment on this block) or be unexported"` to return no errors.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/890)
> Fix some golint issues

- inference/inference.go
- inference/inference_test.go
- Implement RDFS 2 and 3 rules: domain and range implicit class instance
- Restore 100% test coverage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/900)
> Inference: Domain Range Implicit Instances

- query/linkedql/steps.go
- query/linkedql/steps_test.go
- View -> Visit
- ViewBoth -> Both
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/898)
> LinkedQL: Fix Step Names

- query/linkedql/operators.go
- query/linkedql/steps.go
- query/linkedql/steps_test.go
I am not sure yet how to name `Like` and `Regex` as steps yet so I only refactored numeric operators.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/901)
> LinkedQL: Refactor numeric operators to steps

- graph/iterator/materialize.go
Solution to https://github.com/cayleygraph/cayley/issues/911
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/912)
> Fix map allocation bug in materialize.go

- graph/kv/quadstore.go
- graph/memstore/all_iterator.go
- graph/memstore/iterator.go
- graph/memstore/keys.go
- graph/memstore/quadstore.go
- graph/nosql/quadstore.go
- query/path/pathtest/pathtest.go
- query/shape/shape.go
Fixed all lint errors which are:
- unrelated to comments
- unrelated to protobuf generated files
- don't require API changes
Once this PR is merged we can easily add lint on the project as a requirement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/921)
> Lint: Fix easily fixable errors

- .travis.yml
- graph/kv/quadstore.go
- graph/memstore/all_iterator.go
- graph/memstore/iterator.go
- graph/memstore/keys.go
- graph/memstore/quadstore.go
- graph/nosql/quadstore.go
- lint.sh
- query/path/pathtest/pathtest.go
- query/shape/shape.go
Depends on #921
- Created a bash script to execute for linting all files and ignoring show-stopper errors
- Added the lint check to the Travis CI config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/922)
> Lint: Configure CI

- query/linkedql/property_path.go
- query/linkedql/steps/steps_test.go
In steps_test, update all tests to use valid IRIs and fix all lint warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/926)
> LinkedQL: Better Steps Test

- query/linkedql/steps/match.go
- query/linkedql/steps/match_test.go
- query/linkedql/steps/test-cases/match-exact.json
- Brake down code of Match step
- Add documentation for logic applied
- Support recursive matching of nested objects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/916)
> LinkedQL: Fix recursive matching for Match step

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/950)
> Update Freebase's links

- CODEOWNERS
- README.md
Closes #963
I can't currently merge because of branch protections.
Note that I don't have permission to see the configuration for branch protections configuration, but I _think_ this is all that is needed for me to merge.
@dennwc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/964)
> Add eraserhd to CODEOWNERS

- docs/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/944)
> Fix the link for k8s usage

- .gitignore
- .travis.yml
- graph/sql/cockroach/cockroach.go
- graph/sql/mysql/mysql.go
- graph/sql/postgres/postgres.go
- graph/sql/sqlite/sqlite.go
- query/path/morphism_apply_functions.go
- schema/schema.go
- vet.sh
Closes #953 .
Thanks @oxisto for that PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/965)
> Use go vet on 1.17

- graph/iterator/resolver.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/981)
> chore: use copy(to, from) instead of a loop

- CONTRIBUTORS
- graph/kv/bbolt/bolt.go
- graph/kv/bbolt/bolt_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/975)
> Support coreos bolt fork
