graph/leveldb/quadstore.go
In LevelDB's createKeyFor method we allocate size for 3 hashes but append 4 hashes. Eventhough append handles it intelligently, the code is misleading.
CLA already signed, PR ready for review
=> Allocate 82 bytes instead of 62 bytes in LevelDB's CreateKeyFor method

cayley.go, cayley_test.go, db/db.go, writer/single.go
Previously we silently dropped portions or all of a block when a duplicate quad is found. We still fail now, but we tell someone.
Fixes #201.
=> Ensure callers get errors when they happen

graph/bolt/quadstore.go, graph/leveldb/quadstore.go, graph/memstore/quadstore.go, graph/mongo/quadstore.go, graph/quadwriter.go
Previously, an incorrectly initialised Delta (omission of Action) would
result in an Add operation. Make that detectable and return an error.
=> Make graph.Delta zero state invalid for use

cayley_test.go, graph/mongo/quadstore.go
(This is a second PR for a subset of a previous PR that failed on travis because of the mongo versions - see below).
This PR prevents empty values from nodes that are not found from being added to the cache when the mongo backend is used. I was seeing almost exactly what issue #130 was describing and decided to sit down and debug my way through it. Removing the cache logic from the NameOf function pointed me in the right direction. The logic previously was adding to the cache even if the node was not found, which was then providing the empty strings I was seeing during the queries. It will now prevent a not found node from being added to the cache.
I tested these locally against mongo version `2.6.5` and the tests passed (`go test -v -backend=mongo ./...`)! My previous PR (#179) has the …
=> Prevent empty values in cache (using mongo)

graph/bolt/quadstore.go
We don't test for dups or absences in other backing stores AFAICS. It would be nice to harmonise the approaches used in each so that this kind of check and logging or error return can be done elsewhere.
=> Provide informative logging for dups/absences

cayley_test.go, db/repl.go, db/repl_test.go, http/query.go, query/gremlin/gremlin_test.go, query/gremlin/session.go, query/mql/mql_test.go, query/mql/query.go, query/mql/session.go, query/session.go, query/sexp/session.go
Also revert the data type returned by queries to interface{} (the change made sense at the time).
=> Make query/... interfaces more idiomatic

docs/Configuration.md, graph/bolt/quadstore.go, graph/iterator/mock_ts_test.go, graph/leveldb/quadstore.go, graph/memstore/quadstore.go, graph/mongo/quadstore.go, graph/quadstore.go, graph/quadwriter.go, writer/single.go
Add command line option to ignore duplicated quad when loading and ignore missing quads when deleting (two different options) as discussed in issue #201
The command line options are:
* -noerrdup to ignore duplicate
* -noerrdel to ignore missing
This is my first contribution to a go project so forgive me if some choice are not in line with the go coding style
Also note that leveldb doesn't actually detect duplicated line in the same block because is loaded in the db with the same batch. I don't know the impact of such bug.
=> Add options to ignore duplicate or missing quad

cayley.go, cayley_test.go, http/write.go, internal/decompressor.go, internal/decompressor_test.go, quad/decompressor.go
Move the decompression detection to quad (it seeming to be the most logical place for it) and support uploading compressed files through http.
=> fix decompressing for http

.travis.yml, Godeps/Godeps.json, Godeps/Readme
These dependencies can be loaded into your $GOPATH simply executing
`godep get`. This will allow builds to become reproducible, without
getting in the way of those wanting to consume parts of the project's
source code as a library.
As per the discussion in #234.
=> store dependencies' versions with godep

graph/bolt/bolt_test.go, graph/gaedatastore/quadstore_test.go, graph/iterator.go, graph/iterator/and_iterator.go, graph/iterator/and_iterator_optimize.go, graph/iterator/and_iterator_optimize_test.go, graph/iterator/and_iterator_test.go, graph/iterator/query_shape_test.go, graph/leveldb/leveldb_test.go, graph/memstore/quadstore_test.go, graph/mongo/indexed_linksto.go, graph/mongo/iterator.go, graph/mongo/lru.go, graph/mongo/quadstore.go, graph/mongo/quadstore_iterator_optimize.go, graph/result_tree_evaluator_test.go, query/gremlin/build_iterator.go, query/mql/build_iterator.go, query/sexp/parser.go
This is actually a more general optimization for a lot of backends, I'm just implementing it on Mongo first because it'll be easy to measure.
Mongo is also doing many size-fetching roundtrips which are unnecessary and slowing down baseline query speed a lot. So that needs to be fixed too.
The optimization is this: currently, while the indexes are built with prefixes, we're not taking advantage of that fact. This reduces the size of a lot of potential sets and speeds up queries a lot as a result.
This is a fairly naive implementation of the similar concept for Mongo. 
Benchmarks are these:
```
$ benchx mongo_indexed.benchstart mongobench.post
benchmark                                   old ns/op      new ns/op      delta	mult
BenchmarkNamePredicate                      25507744 …
```
=> Mongo Indexed LinksTo

graph/iterator.go, graph/mongo/indexed_linksto.go, graph/mongo/quadstore_iterator_optimize.go
A linkage is a direction/value pair, and that's all. A set of these can
have helper functions and the like. Cleans up some assumptions of
functionality that isn't useful (yet).
Refactor of a new introduction.
=> Clean up Linkage definition

imports.go
This small PR allows opening a database through Go code (#208)
**Usage Example**
```
package main
import "github.com/google/cayley"
store, err := cayley.NewGraph("bolt", "/home/mentalow/mexican_coke_db", nil)
if err != nil {
log.Fatalln(err)
}
```
(CLA Accepted)
=> Allow opening a database (bolt, leveldb, mongo) through Go API

static/css/query_editor.css
It was very frustrating to use the visualisation feature of Cayley, as the vis box was tiny and waste a lot of space. I widened the space to 100% of the viewable DOM. This makes it much more pleasant to use.
Before:
After:
I have signed the Google CLA.
=> Widened visualisation box to 100%

.travis.yml
This is currently breaking CI. We should ultimately find a better place
to download this binary, because Google doesn't seem to host old
versions for very long.
=> travis.yml: bump appengine dependency

graph/leveldb/iterator.go
in "po", the ordering is {"predicate","object","subject","label"} thus the offset of label is 3*hashSize+2
=> Fixed multiplier for position of "label" in case of "po" key entry

graph/iterator/and_iterator_optimize.go, graph/iterator/and_iterator_optimize_test.go
If all the subiterators of an And iterator are Alls, we can return the first one. This hinders other potential optimizations (collapsing of queries, perhaps)
=> Add check for multiple all iterators

CONTRIBUTORS, graph/path/morphism_apply_functions.go, graph/path/path.go
```
CHANGES: 
Added more comments, converted logical operations to (hopefully)
consistent 'route' metaphor, and moved all AND(iterator, iterator)
stanzas out into a single join() function that is more descriptive of
what's actually happening
```
Over the past few months, I've been working on a side-project involving some very extensive changes to Cayley to make it nicer to work with as a Golang library. Notably, after deleting 35k lines of *stuff*, I had to add fields to the Quad structure<sup>1</sup>.  That particular project is on hold for the moment, so I can now port<sup>2</sup> back improvements from that project to Cayley.
This section of Cayley, in particular, boggled me for days when I first read it-- this was prior to @barakmich's talk on the database internals and it took …
=> Refactor for readability

docs/Overview.md
When using commands :a and :d the order of subject, object and predicate are in reverse of how is it written in the Overview.md
=> Order of parameters when using :a and :d are switched

README.md
Easy typo fix in build script. When creating a directory tree to host google project a 'c' was missing on 'src/github.com/google'
See change in line 42 of README.md
=> Typo fix when building cayley from scratch

cmd/cayley/cayley.go, exporter/exporter.go, internal/dump.go
My first attempt at writing/modifying go code, so forgive possible egregious idiomatic golang mistakes. So here it is.
PR Adds exporting capabilities for backup/migration/visualization
./cayley dump -config=foo.cfg -dump=backup.nq -dump_type=nquad
**Types:** nquad / json / [gml](https://en.wikipedia.org/wiki/Graph_Modelling_Language) / [graphml](https://en.wikipedia.org/wiki/GraphML) (last two experimental)
**Output:** to file, gzipped file (when .gz extension used), or "-" for stdout
Solves #176 too.
=> Adds exporting capabilities

graph/transaction.go, graph/transaction_test.go, writer/single.go
It basically allows to add and remove the same quad in a transaction without failing and without depending on the underlying backend. See tests for more insights on what that's doing.
(CLA Accepted)
=> Improve Transaction: deduplicate quads, allow adding/removing a quad in the same tx

graph/sql/quadstore.go
When `tx.Exec` fails and an error is returned, result is nil. Thus, `result.RowsAffected()` panics.
* Add a missing return statement in the error test.
* Add a second missing return statement just below to return the proper error message if we can't execute `RowsAffected` instead of saying that the triple doesn't exist.
(CLA Accepted)
=> Fix NPE in SQL Quadstore

data/testdata.nq, graph/path/morphism_apply_functions.go, graph/path/path.go, graph/path/path_test.go, query/gremlin/build_iterator.go, query/gremlin/gremlin_test.go, query/gremlin/traversals.go
We were building iterators the same way in two places; the gremlin-esque path library and the Gremlin JS library. The latter now depends on the former.
This means two really great things: 1) the path library now has feature parity with the JS (yay) and 2) new features only need a single implementation in Go, and can easily be exposed in javascript.
The new context being routed through path.Path is in pursuit of a future feature; I started trying to do that and got diverted into doing a refactor.
=> query/gremlin: Refactor in terms of graph/path

graph/sql/quadstore.go
subject, predicate, object and labels are not indexed, thus, using a where clause on these fields for the DELETE statement does a full-table scan. Using *_hash columns instead will use the indexes.
=> Fix SLOW DELETEs

imports.go
This is a shortcut for those that are not using the label field. It can
become very verbose always calling Quad with an empty string as the last
parameter.
I've signed the CLA.
=> add Triple function

graph/sql/quadstore.go
Happens when the database could not be opened. Introduced by e849da9.
Example:
```
E1206 19:31:25.879755 06891 quadstore.go:59] Couldn't open database at host=127.0.0.1 sslmode=disable: &pq.Error{Severity:"FATAL", Code:"3D000", Message:"database \"user\" does not exist", Detail:"", Hint:"", Position:"", InternalPosition:"", InternalQuery:"", Where:"", Schema:"", Table:"", Column:"", DataTypeName:"", Constraint:"", File:"postinit.c", Line:"794", Routine:"InitPostgres"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x42b8fa]
1: running
sql      sql.go:504        (*DB).Close(0, 0, 0)
sql      quadstore.go:69   createSQLTables(#3, 0x1e, #1, 0x1960000, 0xc82010a000)
graph    quadstore.go:185  InitQuadStore(#2, 0x3, #3, 0x1e, #1, 0, 0) …
```
=> Fix NPE in SQL initialization

data/testdata.nq, docs/GremlinAPI.md, graph/path/morphism_apply_functions.go, graph/path/path.go, graph/path/path_test.go, query/gremlin/build_iterator.go, query/gremlin/gremlin_test.go, query/gremlin/traversals.go
After the refactor, it's now super easy to extend the gremlin side of things again.
This change adds `.LabelContext([path])` to the API and documentation.
With a context, we can now build and modify the way traversals get built, in this case, restricting them to only being on some subgraph.
This means the label field in quad is now exposed.
=> query/gremlin, graph/path: Add support for querying with labels

graph/memstore/iterator.go, graph/memstore/quadstore.go
This results in a measurable performance improvement (~ 10% better) on a large test suite due to the number of iterators created
CLA signed and submitted
=> Make call to `Sprintf` lazy

query/gremlin/environ.go
This patch works for both old and new version. Supersedes #376.
=> Fix interface conversion in Gremlin

graph/path/morphism_apply_functions.go, graph/path/path.go, graph/path/path_test.go
Implemented Save analogs that does not require predicates to exist.
#353 depends on this functionality.
I have signed the CLA.
=> path: Added SaveOptional

graph/path/path_test.go
=> Add SaveOptional() to save predicates if they exist, and add the

graph/mongo/lru.go, graph/mongo/lru_test.go
Added RWMutex on mongo cache to prevent Fatal Error: concurrent map read and map write on Go >= 1.6.
And a test that throws a panic with current code and go >= 1.6
```
fatal error: concurrent map read and map write
goroutine 11 [running]:
runtime.throw(0x374e80, 0x21)
/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc8200d6d88 sp=0xc8200d6d70
runtime.mapaccess2_faststr(0x254800, 0xc820016780, 0xc8200cc010, 0x4, 0x49e728, 0x4)
/usr/local/go/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc8200d6de8 sp=0xc8200d6d88
github.com/drzippie/cayley/graph/mongo.(*cache).Get(0xc820012320, 0xc8200cc010, 0x4, 0x0, 0x0, 0xf4909)
/Users/drzippie/go/src/github.com/drzippie/cayley/graph/mongo/lru.go:55 +0x67 fp=0xc8200d6e58 sp=0xc8200d6de8
github.com/drzippie/cayley/graph/mongo.(*cache).Put(0xc820012320, …
```
=> Added sync.RWMutex to mongo cache to prevent: fatal error 

graph/path/path.go
This allows for construction of sub-Paths, and then cloning to use them under multiple `And`s or `Or`s.
=> Add Clone() to Path for easier reuse of Path segments

graph/quadwriter.go, graph/quadwriter_test.go
The three error checkers in **graph** were missing the `.Err` for their final comparisons.
=> graph: fix Is*(err error) checkers to properly compare against *DeltaError

Dockerfile, Godeps/Godeps.json
We can see in https://quay.io/repository/cayleygraph/cayley that recent builds are failing.
I found out that there is a missing dependency, so this fix amounts to adding it to [Godeps/Godeps.json](https://github.com/cayleygraph/cayley/blob/master/Godeps/Godeps.json).
I also updated the Dockerfile to use relative imports, as this improves readability.
=> Fix Docker building

appengine/app.yaml, internal/db/repl.go
internal/db/repl.go is not used by the appengine deployment, however the
file is included in the general build. This commit adds the necessary
exclusionary build tag for appengine, and updates app.yaml to the latest
go API (1.6.3) available on appengine.
=> appengine: add build constraint

.travis.yml, appengine/.gitignore, appengine/README.md, appengine/app.flexible.yaml, appengine/app.yaml, appengine/appengine.go, appengine/main.go, appengine/sync-assets.sh, glide.lock, graph/gaedatastore/iterator.go, graph/gaedatastore/quadstore.go, graph/gaedatastore/quadstore_test.go
Ran aefix against the gaedatastore and added some documentation to the
appengine folder along with an example for deploying to the traditional
and flexible environments.
=> appengine: updating dependency paths and adding documentation

graph/path/path.go, graph/path/path_test.go
This is a follow-up to a [previous issue](https://discourse.cayley.io/t/should-traversal-methods-change-their-receiver-path/308).
Said issue reported on path variables in Gremlin/javascript changing as new
paths were created as extensions from them.  This issue was resolved with
a subsequent [PR](https://github.com/cayleygraph/cayley/commit/cf824fe4bb9b5f64296c320f06febc3c33dbc9e0).
The problem, though, lies deeper.  Using cayley as a library and executing
a similar query pattern, the same results appear:
```
func main() {
store, _ := cayley.NewGraph("leveldb", "/path/to/leveldb.db", nil)
alice_path := path.StartPath(store, quad.IRI("alice"))
alice_pre, _ := alice_path.Iterate(nil).AllValues(nil)
fmt.Println("alice:", alice_pre)    // alice is <alice>
alice_follows_path := …
```
=> Clone receiver paths

appengine/appengine.go, cmd/cayley/cayley.go, integration/integration_test.go, internal/db/repl.go, internal/http/query.go, query/gremlin/environ.go, query/gremlin/gremlin_test.go, query/gremlin/session.go, query/mql/mql_test.go, query/mql/session.go, query/session.go, query/sexp/session.go
Change interfaces for query languages.
* use context for cancellation and timeouts
* specify exact type of results
* separate interface for REPL
=> query: Refactor interfaces

graph/iterator.go, graph/iterator/regex_iterator.go, graph/path/morphism_apply_functions.go, graph/path/path.go, graph/path/path_test.go
Provides a new filtering path `.Regex`. The implementation largely mirrors that of `.Filter`
=> Implement regex filter as iterator

graph/mongo/quadstore.go
This PR allows users to pass Cayley an optional mgo session to use for connecting to Cayley.  When the session is passed, a new connection is not dialed.  This provides an advantage for users managing many concurrent requests, who have already implemented logic to manage a pool of mgo sessions outside of Cayley.
=> Ability to pass the Mongo Backend an externally managed session.

glide.lock, glide.yaml
Container wouldn't build, citing the missing dependency. This
PR fixes that.
=> Add missing gojsonld dependency to glide

glide.lock, glide.yaml, graph/gaedatastore/quadstore_test.go, graph/mongo/quadstore_test.go, graph/sql/quadstore_test.go, internal/dock/dock.go
Remove glide Docker dependencies, make Docker an optional dependency, add build tags for docker and appengine tests.
=> Fix build tags

graph/path/morphism_apply_functions.go
If we're going to remove them anyway, then adding a bunch of alls into a And iterator slows down Optimize() -- so let's just never make them from the query side in the first place.
=> Remove extraneous alls

graph/graphtest/graphtest.go, graph/path/pathtest/pathtest.go, graph/sql/cockroach.go, graph/sql/cockroach_test.go, graph/sql/mysql.go, graph/sql/mysql_test.go, graph/sql/optimizers_test.go, graph/sql/postgres.go, graph/sql/postgres_test.go, graph/sql/quadstore.go, graph/sql/sql_iterator.go, graph/sql/sql_link_iterator.go, graph/sql/sql_link_iterator_test.go, graph/sql/sql_node_intersection.go, graph/sql/sql_node_iterator.go, integration/integration_test.go
Adds `flavor` option to sql backend. Allowed values: `postgres` (default), `mysql`, `cockroach`.
**TODO**
=> Support SQL flavors: Mysql, CockroachDB

graph/quadwriter.go, internal/http/accept.go, internal/http/http.go, internal/http/write.go
* New api endpoints: `/api/v2/read,write,delete`.
* All endpoints use streaming - supports large import/export operations.
* Selects format based on Accept or Content-Type HTTP header.
* Supports gzip compression (Accept-Encoding and Content-Encoding HTTP headers).
=> http: use formats - implement write api v2; resolves #176

README.md, docs/Quickstart-As-Application.md, internal/db/db.go
Hopefully made the quickstart application a bit more clear for running init and then load/repl.
Also did a small fix of returning a more specific error message when a database file can not be opened. Not sure if this is necessary since there is a new CLI on its way.
And explained the binding on localhost and host 0.0.0.0 if people try to access it on a virtual machine / test-server.
=> Issue #286 init db and config documentation

docs/Quickstart-As-Application.md
I found a typo in Quickstart-As-Application.md.
MPL => MQL
=> docs: fix a typo in Quickstart-As-Application.md

docs/Configuration.md
127.0.0.1 is not equal to all interfaces. And all interfaces shouldn't be the default because of security reasons. I updated this in the docs and I also updated this in the new_cli branch that I will push later.
This info was already updated before in the quickstart for application.
=> Updated documentation based on Issue #349

data/30kmoviedata_gephi_meta.nq, docs/GephiGraphStream.md, docs/HTTP.md, graph/iterate.go, internal/gephi/stream.go, internal/gephi/stream_test.go, internal/http/http.go, schema/schema.go, voc/schema/schema.go
Implement GraphStream HTTP endpoint.
**Support two modes:**
* "Raw" nodes and quads
* Nodes with properties (use metadata in graph to inline some properties) 
Example of the last mode for movies dataset:
P.S. I'm not a visualization expert :P
**TODO:**
More information in `docs/GephiGraphStream.md`.
Note: there is a [bug](https://github.com/gephi/gephi/issues/1668) that prevents loading over 200k nodes.
=> Gephi support

graph/mongo/quadstore.go, graph/mongo/quadstore_test.go
Reorder tx operations to avoid broken quads for concurrent readers.
=> mongo: reorder tx operations

.goxc.json, .relego.yaml, glide.lock
Bump the Bolt dependency and (in so doing) support arm64
=> Switch release tooling from goxc to relego

docs/Quickstart-As-Application.md
When running the example, I had as a result:
```shell
I0420 21:27:49.606456    2853 cayley.go:67] Cayley version: 0.7.0-alpha (dev snapshot)
I0420 21:27:49.607930    2853 database.go:174] using backend "memstore" (./data/30kmoviedata.nq.gz)
Serving Gephi GraphStream at http://localhost:/gephi/gs
I0420 21:27:49.610088    2853 http.go:59] listening on 0.0.0.0, web interface at http://0.0.0.0
Error: listen tcp: address 0.0.0.0: missing port in address
```
Adding the :port to the command line works:
```shell
cayley http --dbpath=./data/30kmoviedata.nq.gz --host 0.0.0.0:64210
I0420 21:28:17.251777    2870 cayley.go:67] Cayley version: 0.7.0-alpha (dev snapshot)
I0420 21:28:17.253495    2870 database.go:174] using backend "memstore" (./data/30kmoviedata.nq.gz)
Serving Gephi GraphStream at …
```
=> The -host option was missing the port argument

cmd/cayley/cayley.go, graph/quadwriter.go
Errors on writing duplicate quads is confusing for most new users. I propose to ignore duplicates by default.  
Such error should be caused by per-transaction operations like compare-and-insert, not in the data import code path.
=> Ignore duplicate quads by default

glide.lock, glide.yaml, graph/gaedatastore/quadstore_test.go
This also bumps our deps, which is always a good thing.
=> Fix glide story; ignore docker deps, `glide.lock` is now sane

cmd/cayley/command/dedup.go, graph/bolt/quadstore.go, graph/bolt2/quadstore.go, graph/gaedatastore/quadstore.go, graph/iterator/all.go, graph/iterator/count.go, graph/iterator/count_test.go, graph/iterator/materialize.go, graph/iterator/mock_ts_test.go, graph/iterator/recursive.go, graph/iterator/recursive_test.go, graph/iterator/unique.go, graph/iterator/value_comparison_test.go, graph/leveldb/quadstore.go, graph/mongo/quadstore.go, graph/proto/primitive_helpers.go, graph/quadstore.go, graph/sql/quadstore.go
As per an old discussion, we should not allow to pass arbitrary data types as `graph.Value`.
Also, since we need these values to be comparable anyway, promote `Keyer` interface as a part of `Value`.
=> Make graph.Value safe again

docs/Quickstart-As-Application.md
Update example start up command. The existing example results in an error. It appears --port was added as a separate argument later on.
=> Fix example startup command

docs/HTTP.md
Before (left) and after (right):
=> Remove "angry highlighting" from JSON examples

graph/path/morphism_apply_functions.go, graph/path/path.go, graph/path/pathtest/pathtest.go, query/gizmo/gizmo_test.go, query/gizmo/traversals.go
This PR adds support for querying for labels from the Gizmo API, by adding a morphism which returns all labels associated with the quad.
=> Add labels morphism and Gizmo API

internal/http/http.go
This PR adds CORS headers to responses on the `/gephi/gs` endpoint.
=> Set CORS headers on gephi stream

graph/bolt/quadstore.go, graph/bolt2/bolt.go, graph/gaedatastore/quadstore.go, graph/kv/quadstore.go, graph/leveldb/quadstore.go, graph/memstore/quadstore.go, graph/mongo/quadstore.go, graph/quadstore.go, graph/sql/quadstore.go
Remove code that is no longer used after #570
Closes #537
=> Remove unused code

AUTHORS, CONTRIBUTORS, graph/iterator/recursive.go, graph/iterator/recursive_test.go, graph/path/morphism_apply_functions.go, graph/path/path.go, graph/path/pathtest/pathtest.go, query/gizmo/environ.go, query/gizmo/finals.go, query/gizmo/traversals.go
First stab at adding an optional parameter max recursion depth for `FollowRecursive`.
Also noticed `MaxRecursiveSteps ` wasn't being used anywhere and decided to add a max default recursive depth of 50.
Related Issue: https://github.com/cayleygraph/cayley/issues/624
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/639)
=> Add optional max recursion depth to FollowRecursive

graph/nosql/elastic/elastic.go, graph/nosql/mongo/mongo.go, graph/nosql/nosql.go, graph/nosql/quadstore.go, graph/nosql/shapes.go, graph/path/pathtest/pathtest.go, graph/shape/shape.go, graph/sql/mysql/mysql.go, graph/sql/optimizer.go, graph/sql/postgres/postgres.go, graph/sql/quadstore.go, graph/sql/shape.go, query/gizmo/environ.go, query/gizmo/gizmo_test.go
Implement a subset of regexp  - a wildcard query (`LIKE` in SQL). Resolves #664.
At the same time enable regexp optimization for all backends.
Wildcards are exposed in path lib:
```golang
p.HasFilter(quad.IRI("name"), false, shape.Wildcard{
Pattern: `An%`,
})
```
And in Gizmo:
```javascript
g.V().Has("<name>", like("An%"))
```
=> Support wildcards and regexp queries

README.md, docs/Configuration.md, glide.lock, glide.yaml, graph/all/all.go, graph/graphtest/graphtest.go, graph/iterator/value_comparison.go, graph/nosql/elastic/elastic_test.go, graph/nosql/iterator.go, graph/nosql/mongo/mongo_test.go, graph/nosql/nosqltest/nosqltest_all.go, graph/nosql/nosqltest/nosqltest_nosql.go, graph/nosql/ouch/README.md, graph/nosql/ouch/backend.go, graph/nosql/ouch/backend_js.go, graph/nosql/ouch/couch.go, graph/nosql/ouch/couch_test.go, graph/nosql/ouch/none_test.go, graph/nosql/ouch/ouch.go, graph/nosql/ouch/ouch_test.go, graph/nosql/ouch/pouch.go, graph/nosql/ouch/pouch_test.go, graph/nosql/ouch/values.go, graph/nosql/quadstore.go, graph/nosql/shapes.go, graph/nosql/value_test.go, graph/sql/cockroach/cockroach_test.go, graph/sql/mysql/mysql_test.go, graph/sql/postgres/postgres_test.go, internal/dock/dock.go
Implement CouchDB and PouchDB backends based on NoSQL meta-backend.
CouchDB backend will work on Go side, while PouchDB can be used with GopherJS which adds a possibility to run Cayley in browser.
Resolves #655
=> Support for CouchDB and PouchDB backends

docs/Contributing.md, graph/sql/cockroach/cockroach.go, graph/sql/cockroach/cockroach_test.go
This flattens the CockroachDB driver to be mostly self-contained for insertions instead of leaning on the Postgres driver. I think that's the best option here since the tradeoffs between the two are quite different, and it isn't a large amount of code anyway.
I've run all the docker & integration tests; all pass except for TestCockroach/qs/integration, which fails both before and after this change (with `transaction is too large to commit: 100005 intents`) and I don't believe is affected by this change.
=> Optimise CockroachDB backend

graph/sql/cockroach/cockroach.go, graph/sql/cockroach/cockroach_test.go
This was at the behest of CockroachDB engineers who say this is a much
better driver
(https://github.com/cockroachdb/cockroach/issues/17108#issuecomment-368024371).
I'm not sure if this is the kind of thing you're interested in accepting, but it was quite easy to do, and seems to work fine for me in a real situation.
This extends work done in #691.
=> Switch CockroachDB driver from lib/pq to jackc/pgx.

docs/GraphQL.md, query/graphql/graphql.go, query/graphql/graphql_test.go
=> graphql: support un-nesting objects into parent

examples/hello_schema/main.go, graph/graphtest/graphtest.go, query/gizmo/environ.go, query/gizmo/gizmo.go, schema/global.go, schema/schema.go, schema/schema_test.go
=> schema: allow to customize behavior

docs/GizmoAPI.md, query/gizmo/gizmo_test.go, query/gizmo/traversals.go
=> gizmo: expose SaveOptional

examples/hello_schema/main.go
If TempFile is used cayley.NewGraph complains about
tmpfile.Name() not being a dir.
=> hello_schema: replace TempFile with TempDir

docs/Contributing.md, internal/dock/dock.go
When I run all go tests in cayley according to docs/Contributing.md, I notice all backend implementations are created by docker. But if I don't have the relevant image at local, the tests will skip. the code only do some operation about backend implementations containers like this: create container from a image -> start container -> inspect container and not pull image from remote repository first. So I do a little change here. Wish this will help. 
Last time I have pull request fail because of CI, So I rebase on top of the new master.
=> Fix gotest is related to docker

graph/iterator/optional.go
TagResults() is propagating only the sub iterator tags.
At the very least this was causing an issue with @id tagged field population using Config.LoadTo() to the following structure
```
type Node struct {
ID quad.IRI `quad:"@id"`
Related []*Node `quad:"related"`
}
```
for which the following iterator tree is generated
```
it = {github.com/cayleygraph/cayley/graph.Iterator} 
data = {*github.com/cayleygraph/cayley/graph/iterator.And} 
= {github.com/cayleygraph/cayley/graph/iterator.And} 
uid = 37
tags = {github.com/cayleygraph/cayley/graph.Tagger} 
internalIterators = {[]github.com/cayleygraph/cayley/graph.Iterator} len:1, cap:20
= {github.com/cayleygraph/cayley/graph.Iterator} 
data = {*github.com/cayleygraph/cayley/graph/iterator.Optional} 
= …
```
=> Fix Optional iterator not propagating own tags

Gopkg.lock
Cayley uses a DeletableBloomFilter for kv stores, which may cause a panic when loading a database due to an off-by-one error. In particular, you will see something like this (using the latest release binary):
```
I1019 13:01:18.852254   15348 cayley.go:63] Cayley version: 0.7.4 (431ee2850fa29f8f7dfa0de6a03c07237871d504)
I1019 13:01:18.852716   15348 cayley.go:76] using config file: config.yml
I1019 13:01:18.852820   15348 database.go:187] using backend "bolt" (./boltey)
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/cayleygraph/cayley/vendor/github.com/tylertreat/BoomFilters.(*Buckets).setBits(0xc4201c0000, 0x100000078, 0xc400000001)
/go/src/github.com/cayleygraph/cayley/vendor/github.com/tylertreat/BoomFilters/buckets.go:101 +0x128 …
```
=> Update BoomFilter to avoid Cayley panicing

graph/graphmock/graphmock.go
Would always return value of given node, even if not present in mock data.
=> Fix mock store ValueOf implementation never returning nil

graph/kv/quadstore.go, graph/quadstore.go
Requirement exposed by https://github.com/cayleygraph/cayley/pull/741
Add NamesOf to the BatchQuadStore interface.
Add notes that NamesOf and ValuesOf have their names the wrong
way around.
Add a dummy NamesOf to kv/QuadStore to avoid breaking it's
BatchQuadStore implementation.
=> Add NamesOf to the BatchQuadStore interface

AUTHORS, CONTRIBUTORS, graph/graphtest/graphtest.go, graph/kv/indexing.go
When reinserting a previously deleted quad, and attempting to then delete it a quad does not exist error was given for the the kv stores, issue was retrieval of the primitive from the log was finding the prviously deleted, not the previously inserted quad. Change retrieval from the log to iterate in reverse to ensure the latest is retrieved when multiple hits. Added unit test.
=> fix for deletion of reinserted causing a quad does not exist error

docs/Configuration.md, go.mod, go.sum, graph/nosql/mongo/mongo.go
Switching Cayley's mongo driver from `gopkg.in/mgo.v2` to `github.com/globalsign/mgo`
We initially ran into an issue using Cayley with a mongo connection string that included the `ssl=true` parameter eg. `mongodb://user:pass@host:27017/db?ssl=true`
The new driver is compatible with the existing code, and allows us to use the required connection string query param.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/773)
=> Update version of mongo driver

graph/kv/indexing.go, graph/kv/kvtest/kvtest.go, graph/kv/quadstore.go
This change enables test for KV without the Bloom filter, which uncovers the #771 and fixes it by properly skipping removed quads when the Bloom returns false positives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/774)
=> kv: Properly skip removed quads

schema/loader_test.go, schema/schema_test.go, schema/writer.go, schema/writer_test.go
Support custom types based on primitive Go types when writing quads with the schema library.
Fixes #768
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/775)
=> schema: Support typedefs when writing structs

graph/shape/path.go, graph/shape/shape.go, graph/shape/shape_test.go, query/graphql/graphql_test.go
This change removes `shape.Optional` and merges it into `shape.IntersectOpt`. This allows to properly optimize queries that contain only optional branches.
Fixes #740
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/776)
=> Fix optimization of optional intersections

imports.go
Please take a look.
TBH I think that it's probably wrong for them to be here, but they are, so they should match perfectly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/800)
=> cayley: use alias to make import helpers perfect matchers

graph/memstore/quadstore.go, graph/quadwriter.go, internal/load.go, quad/dot/dot.go, quad/gml/gml.go, quad/graphml/graphml.go, quad/json/json.go, quad/jsonld/jsonld.go, quad/nquads/nquads.go, quad/pquads/pquads.go, quad/rw.go, schema/writer_test.go
Include the `WriteQuads` (batch) to the `quad.Writer` interface. And add deprecation notes for `WriteQuad` (single).
This will eventually allow faster data import for the backends.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/802)
=> Require quad writers to have a batch method

cmd/cayley/command/database.go, graph/gaedatastore/quadstore.go, graph/graphmock/graphmock.go, graph/graphtest/graphtest.go, graph/graphtest/integration.go, graph/kv/indexing.go, graph/log/graphlog.go, graph/memstore/quadstore.go, graph/memstore/quadstore_test.go, graph/nosql/quadstore.go, graph/quadstore.go, graph/shape/shape_test.go, graph/sql/quadstore.go, internal/load.go
Expose a `quad.Writer` constructor on `QuadStore` to allow backend implementations to optimize quad import.
Also, implement the first set of optimizations for KV backends. Results for a 30K quads file:
```
benchmark                     old ns/op     new ns/op     delta
BenchmarkBolt/qs/import-8     3212907       490386        -84.74%
BenchmarkLeveldb/qs/import-8  4199793       231921        -94.48%
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/803)
=> Optimize batch import to KV backends

server/http/api_v2.go
non-breaking convenience change to allow `HandlerWrapper`s to be set up with the API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/808)
=> add wrappers as param to api constructor

cmd/cayley/cayley.go, go.mod, go.sum, graph/kv/bolt/bolt.go, graph/kv/indexing.go, graph/kv/iterators.go, graph/kv/metrics.go, graph/kv/quad_iterator.go, graph/kv/quadstore.go, graph/kv/quadstore_test.go, graph/shape/shape.go
Previously KV backends were using two indexes for quads:
- `Subject` index
- `Object` index
Each of those include a list of all quads including the same subject/object in each entry.
This works good for small/medium datasets, but presets a problem for huge datasets like Freebase. For quads like `<x> <rdf:type> <y>` the object index for `<y>` may become _very_ large. Having in mind that modification of a single index entry requires loading it into memory, this may lead to OOM issues, as in #815.
This pull request changes the indexes to:
- `Subject`, `Predicate` index
- `Object`, `Predicate`, `Subject` index
The first index should improve query performance for forward traversals in large datasets.
The second index solves the super-node issue that leads to OOM by building an index specific …
=> Change indexing strategy for KV backends

cmd/cayley/command/repl.go, graph/graphtest/integration.go, internal/http/query.go, internal/repl/repl.go, query/gizmo/gizmo.go, query/gizmo/gizmo_test.go, query/graphql/graphql.go, query/mql/mql_test.go, query/mql/session.go, query/session.go, query/sexp/session.go, server/http/api_v2.go
Current query interface (in Go) is weird. The user must know that `Execute` should be called in a goroutine, and then returned values should be `Collated`. This is a very non-intuitive way to expose query results.
This PR defines a new interface that returns a regular iterator. The type of query results is controlled by an option. This way the query language will collate value internally, providing only useful values to the user.
This is a breaking change, since it replaces the old interface completely. However, internal query interface was not documented, and was not intended for external use, so I think it's worth changing anyway.
This change also adds an extendable `Options` parameter to `Execute`, unlocking future progress on #821.
---
This change is [<img …
=> Define and implement a new query interface

graph/path/pathtest/pathtest.go, graph/sql/iterator.go, graph/sql/optimizer.go, graph/sql/shape.go
When optimizing queries for SQL, we missed the fact that `NodesFrom` and derived queries make use of `NextPath` which is not implemented on SQL iterators.
This PR fixes it by emulating the same behavior for both `Next` and `Contains`.
Fixes #724
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/848)
=> Fix NextPath for optimized queries in SQL

query/gizmo/gizmo_test.go, query/gizmo/traversals.go
We were not checking the argument type for `filter()` correctly. This PR adds this check. But if we want to accept string values, we will need another change, similar to how `has()` is implemented.
Fixes #833
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/849)
=> Return error when calling filter() with a wrong type in Gizmo

graph/iterator/recursive.go, graph/path/pathtest/pathtest.go
Currently, `Recursive` when iterating values (`Next`), but fails during lookups (`Contains`).
This PR fixes this behavior by correctly preserving tags of checked values.
Fixes #714
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/857)
=> Tag values correctly in Recursive during Contains

query/gizmo/gizmo_test.go, query/gizmo/traversals.go
- Allow a single IRI in `save()`, plaintext or typed.
- Set a default tag if not specified.
- Do not add `<>` to tags in JSON-LD collation. 
Fixes #856
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/859)
=> IRI fixes for Save in Gizmo

.gitignore, .travis.yml, packrd/dummy.go
Currently, the build of a binary requires a `packr2` command to be run. This PR adds a dummy file to the packr directory expected by the build to allow compiling without packr resources (fallback to FS).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/858)
=> Fix build without packr resources

graph/graphtest/graphtest.go, graph/memstore/quadstore.go
Currently, all backends incorrectly increment node ref count when a duplicate quad is inserted.
This PR adds a test case for this issue (skipped for now) and fixes the behavior for the memstore. For other backends the fix will be way more involved, and deserves a separate PR.
Addresses #737
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/860)
=> Memstore: Don't increment node ref count when duplicate is inserted

query/path/morphism_apply_functions.go, query/path/path.go, query/path/pathtest/pathtest.go
Currently we only allow to trace a single path in `Has`. This PR allows to pass an arbitrary subtree by calling the new `HasPath` helper.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/887)
=> Implement HasPath helper

query/path/morphism_apply_functions.go, query/path/path.go, query/path/pathtest/pathtest.go
Currently `path` library provides a `SaveOptional` helper - this is the only way to use optional path right now. This PR adds a generic `Optional` helper that accepts any other path, allowing to query larger optional subtrees.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/886)
=> Implement Optional path

docs/quickstart-as-application.md
Was perusing the Cayley docs and happened upon this link that didn't work. Years of internet spelunking have steeled me for such moments, so I quickly found the docs, but the whole point of open source is so that someone does that sort of work once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/903)
=> fix links in quickstart-as-application

internal/linkedql/schema/schema.go, query/linkedql/graph_pattern.go, query/linkedql/registry.go, query/linkedql/steps/match.go, query/linkedql/steps/steps_test.go
Depends on #904 
Define a `Match` step in LinkedQL that accepts a subgraph pattern and return entities matching the graph.
Example:
```go
Vertex().Match({ "http://example.org/likes": "http://example.org/bob" })
```
Will return all the entities which have a property pointing to Bob.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/905)
=> LinkedQL: Match

internal/linkedql/schema/schema.go, query/linkedql/property_path.go, query/linkedql/steps/both.go, query/linkedql/steps/has.go, query/linkedql/steps/has_reverse.go, query/linkedql/steps/properties.go, query/linkedql/steps/reverse_properties.go, query/linkedql/steps/steps_test.go, query/linkedql/steps/visit.go, query/linkedql/steps/visit_reverse.go
- Use PropertyPath everywhere it should be
- Make NewPropertyPath return a pointer to allow no properties as a valid PropertyPath
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/928)
=> LinkedQL: Improve PropertyPath

query/linkedql/steps/collect.go, query/linkedql/steps/test-cases/collect.json
Adds a collect step to resolve lists.
The best solution I can come up with so far is: saving tags as quads and then resolve JSON-LD through the From RDF API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/920)
=> LinkedQL: Collect Step

docs/api/swagger.yml, server/http/api_v2.go, server/http/api_v2_test.go
Create a new HTTP resource for namespace rules.
The resource supports getting all registered rules and registering a rule.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/925)
=> Namespace Rules HTTP API

README.md
The current URL http://gremlindocs.com/ points to a parked domain. The actual docs are at https://tinkerpop.apache.org/gremlin.html
We can [skip ci] since this isn't modifying any code and won't affect CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/970)
=> Fix URL pointing to Gremlin docs

README.md
The current URL (https://www.travis-ci.com/cayleygraph/cayley) returns a 404, so update to the correct URL https://app.travis-ci.com/github/cayleygraph/cayley .
Additionally, the image URL redirects to the api.travis-ci.com hostname, so fix that as well.
Since this change isn't modifying any code and shouldn't affect the build, we can [skip ci].
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/969)
=> Fix Travis CI badge URL and landing page URL

go.mod, go.sum
There are 1 security vulnerabilities found in github.com/docker/docker v0.7.3-0.20180412203414-a422774e593b
- [CVE-2015-3627](https://www.oscs1024.com/hd/CVE-2015-3627)
Upgrade github.com/docker/docker from v0.7.3-0.20180412203414-a422774e593b to 1.6.1 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cayleygraph/cayley/972)
=> fix(sec): upgrade github.com/docker/docker to 1.6.1
